In [ ]:
ai = ["Regression","Supervised Learning", "y=mx+c"]
ai

['Regression', 'Supervised Learning', 'y=mx+c']

In [8]:
# ai[2]

# ai[len(ai)-1]

ai[-1]

'y=mx+c'

In [9]:
import numpy as np 

data = np.zeros((3,4))

data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
data2 = np.ones((2,3))
data2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
print(np.empty((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
my_array = np.array([
    [1,2],
    [2,3]
]) 

print(my_array.shape)
print(my_array.size)
print(my_array.dtype)

(2, 2)
4
int64


In [24]:
my_array = np.array([
    [1.1,2.3],
    [2.3,3.4]
]) 

print(my_array.dtype)

float64


In [26]:
my_array = np.array([
    [1.1,2],
    [2,3]
]) 

my_array.dtype


dtype('float64')

In [ ]:
a = [1,2,3]
b = [4,5,6]

a+b

[1, 2, 3, 4, 5, 6]

In [28]:
c = np.array([1,2,3])
d = np.array([4,5,6])
c+d

array([5, 7, 9])

In [30]:
marks = [30,40,50]
marks[0:2] # [30,40]
marks [1:-1]

[40]